# Generated by Django 3.0 on 2020-01-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('leave_on', models.CharField(max_length=200)),
                ('leave_upto', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=200)),
                ('status', models.CharField(default='pending', max_length=200)),
            ],
        ),
    ]
