# Generated by Django 3.0 on 2020-01-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='marksubmit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('assess_no', models.CharField(max_length=200)),
                ('max_mark', models.CharField(max_length=200)),
                ('subject_1', models.CharField(max_length=200)),
                ('subject_2', models.CharField(max_length=200)),
                ('subject_3', models.CharField(max_length=200)),
                ('subject_4', models.CharField(max_length=200)),
                ('subject_5', models.CharField(max_length=200)),
            ],
        ),
    ]
