# Generated by Django 3.0 on 2020-01-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_app', '0002_marksubmit'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendances',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('Date', models.CharField(max_length=200)),
                ('status_h1', models.CharField(max_length=200)),
                ('status_h2', models.CharField(max_length=200)),
                ('status_h3', models.CharField(max_length=200)),
                ('status_h4', models.CharField(max_length=200)),
                ('status_h5', models.CharField(max_length=200)),
            ],
        ),
    ]
